name: Docker CI Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Env Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=ylqjgm/lanraragi
          VERSION=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^([0-9]{1,3}\.){,3}[0-9]{1,4}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi

          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
      - name: Clone
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git
          git clone https://github.com/uparrows/LANraragi_cn.git -b ${{ steps.prepare.outputs.version }} lanraragi
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: build
        uses: docker/build-push-action@v2
        with:
          context: ./lanraragi
          file: ./lanraragi/Dockerfile
          push: true
          platforms: linux/arm
          tags: ${{ steps.prepare.outputs.tags }}
